before_install: cd BackEnd
language: php
php:
- 5.4
script: ls
deploy:
  provider: heroku
  api_key:
    secure: T/+IZhpOlalWUFG6RpcKtXa8wOrhaUgDZs4jUABpGbKefWRpjW5Gqr5mLKVecK9M95/E3HlOoPmv6hL2lgZMIEVG0HzJWRjIgsEoOr3ozE32h3UbtswM9S4e1bCF3qD/es/w3qI1HNo+89GwbqeAMw01Uhul1korojSj8q2eqmUiaA/dLYDO2fLIW/rC+LlH40NmL9dKKA3FaDIHQHwK1NUlf7dik1trV1VtHLaWq9Yl2ycug459Hf/z2ns05vrOQg5Drw5/5RWHBUFs4v8NXpaIgDXmBojOE2pU2Ud3lm/oR4uqE/EimBbcp7u7vjfO0pykRlECdfBzCfgCQwPXSjihRDP0wUGRbcuPQ2rmCF2Aa4TUrJv8gLqaeNC654gLwKLPxgSqEncHqKQr+YN9LbUBZ4p1zSonXpgE+bmPcQPdgzIjSHLwPVo1iZ90oe4bBq69pKEE09ijrwQAvgQpAWL44MNX8gZ7hDEPLen2b1MT1LaLpeCqTDJ+bcJtJqJt8iI2WN8nQoUzJtB3iRBuYI3ssiqHhwOEEHLHYfsCyAcYTnbV+v8OWvoD+f0VVypxO8L0MWJxaZ/eJFN9drtuk/fedvl+ApqKu0+3zrPDWwgv3K+y6mB0dVKTTPjOeB9PAHhcipnDH2LUlrQ7BJDx21Jp0hOaPcH0Lmnyj3Hjqzc=
  app: experiencesampling