before_install: cd BackEnd
language: php
php:
- 5.4
script: ls
deploy:
  provider: heroku
  api_key:
    secure: zcU5jEBHjgvwuvPDruIejWg3ZTV4zC9H28bGvp9f8r9GoHPDpci5a9mB0aj8j9tZ92lpS2nqB+/QKuORagUAPXUQkfzLLS99hH6OimxUfA8lCsi5WJ9Pek8T2cmJAmDwVTzSC26iXzIhr/jBaYudCE1gotwKfsyKf1qwBpgcptZKxL+hfvZriO+BDd2/TMCiaPNLJ4r3WAMKE8PPBy6D9SNEnNBot/6V+IT/zlnxMgKd+YIqExleDr8BKtBwD8T/0XLNBp/xK1b2ULjZCwZIRt/wmN1HcNh7IohlsGxVOmzwxfPWT/Ua41wLMyyPSnfEGumoLCWbphbZMGNtZe2jVmZDLiFFQF1u34Mg1e4fxMUqqNuKxzKOxWU8cotyzyYZRJAOEnvGu+m/xYU7p/BV9Un75CQHITZ3jWD+N7x7SPgxgDKLQYC5L5yI/rldt9JKMobCi7840lcQ1Pb8WrJF+J1mzT6qZuXm3bDrSu6YcIxbNfGRgXjkoCD6MTMWVM1+YYucOq9tkexGWnaZfKG+kzYqYGjhdpCG6ge+gcsTKdxfVR68Y9+fNasowjzb7NOAhNgStGr+blw1AqPGXCU5bsfk2CcfFakzVE59GqmDEy6qRa4jcY/6aPmqvJBIVzx2q7xdKkKyYItkjMN7oaHqyTWXu/hX6Vdi42orell34F8=
  app: experiencesampling
