before_install: cd BackEnd
language: php
php:
- 5.4
script: ls
deploy:
  provider: heroku
  api_key:
    secure: WJyU7HV5tBPu0/0Fr4jvxlYEekU5V4LnmfppUApx0QHlXp/3EJFQXbbR2748PHOsd5s11AxDhlgu423sLvh88qJab9So8AnV3enI7ml9UeWzu9n6WDnZIIeio4GUCTCgr0/gIJeOtxgiCLjag21RTrtAXuJGk8qW8z3H152ScnNnlHq1/URkBb49o3vAdOcKp6LMCeS/sg7LYDVCks+jC93o4cSPU6DwK01rrt0NlcSB2TDb1QRgkPhV3NcxAGj2DUAsOAGlYCv8BRhCW71SOPdWrrMYq3yARzLgwEC4RQtLIZJgNikItSe1DNHlAQ8HAWnXF7Z3B0w817qdSeXH6/R3OSEO6XXXgfx23RlyaJcID6QyIcSvQx4o39Nyu8NmZrjYYF0/Z5EhMD7gHRIDsUlduW8UHhd6FRHfg6dzD675crnZhm4jdfOfm754yha7euv96/88nvVtwOQV+tR0S1u7cImtQwVFqv6sNfZhSNtL80MzpeaO6X5S/6zqae8FxdBvFAYIPl4ajBSx9bpFEeH6s4hrTY32/5Bovp2bjMvhbN2NCrdKtz5/duWqayw0+h1rluJ4zBP6Xr9d3e+wniKJPxLtFf0H1cFheYabchamk0NAg+WROaIB6SxnzNSZJeQ8Yg0nmqfH+yQQV9UDjE80ayktLYNKJKrsLTZZcPk=
  app: experiencesampling
